[package]
name = "stateful-server"
version = "0.2.2"
edition.workspace = true

[dependencies]
turul-mcp-server = { workspace = true }
turul-mcp-protocol = { workspace = true }
turul-mcp-builders = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
turul-mcp-derive = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }