[package]
name = "stateful-server"
version.workspace = true
edition.workspace = true

[dependencies]
turul-mcp-server = { workspace = true }
turul-mcp-protocol = { workspace = true }
turul-mcp-builders = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
turul-mcp-derive = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }
[[bin]]
name = "stateful-server"
path = "src/main.rs"
test = false
